#!/usr/bin/env ruby
require_relative 'tasks/tasks'
require_relative 'config/config'

unless ARGV[0].nil?
  task = case ARGV[0].downcase.to_sym
  when :courierpost_tracking
    CourierpostTracking.new customer_id: ARGV[1]
  when :query
    Query.new query_name: ARGV[1], query_args: ARGV[2..-1]
  else
    puts 'No such task'
  end

  task.run

else
  puts 'No task parameter present'
end
